<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>myrule</name>
  <uuid>2f7d862d-243a-4a1d-973c-80d33cd9796c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Input is "IBM"
then
    set decision to "Good" ;
else 
    set decision to "Bad";
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
